name: Run tests on commit

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Download test data
      run: wget -O data/fastestspeedrun.zip https://owncloud.hpi.de/s/tGKfRrmTUejNhRH/download

    - name: Unpack test data
      run: unzip data/fastestspeedrun.zip -d data

    - name: Install GTest
      run: |
        sudo apt-get update && sudo apt-get install -y libgtest-dev

    - name: Configure
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: |
        cmake --build build --config Debug

    - name: Test
      run: |
        cd build
        ctest -C Debug --output-on-failure --verbose --exclude-regex LargeOnes
